# Generated by Django 2.2.24 on 2021-07-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='students',
            new_name='studen',
        ),
    ]
