# Generated by Django 2.2.24 on 2021-07-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprentices', '0002_remove_apprentices_lesson'),
        ('classes', '0002_auto_20210705_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='studen',
        ),
        migrations.AddField(
            model_name='classes',
            name='students',
            field=models.ManyToManyField(to='apprentices.Apprentices'),
        ),
    ]
