# Generated by Django 2.2.24 on 2021-07-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_auto_20210705_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apprentices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=1000)),
                ('lesson', models.ForeignKey(null=True, on_delete=True, to='classes.Classes')),
            ],
        ),
    ]
