# Generated by Django 2.2.24 on 2021-07-05 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teachers_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='lesson',
        ),
    ]
